### ISSUE TITLE
Gitlab - "cannot modify limit: Operation not permitted" while using the Docker image

### ISSUE THREAD

**Issue by davStar** [lightpharosio/allspark_deployer#1]
Docker Gitlab container restart. 

> docker logs gitlab

 displays the following error:

```
NoMethodError
-------------
undefined method `+' for nil:NilClass

Cookbook Trace:
---------------
  /opt/gitlab/embedded/cookbooks/cache/cookbooks/gitlab/libraries/gitlab_pages.rb:84:in `parse_gitlab_pages_daemon'
  /opt/gitlab/embedded/cookbooks/cache/cookbooks/gitlab/libraries/gitlab_pages.rb:28:in `parse_variables'
  /opt/gitlab/embedded/cookbooks/cache/cookbooks/package/libraries/helpers/settings_helper.rb:174:in `block in generate_config'
  /opt/gitlab/embedded/cookbooks/cache/cookbooks/package/libraries/helpers/settings_helper.rb:172:in `each'
  /opt/gitlab/embedded/cookbooks/cache/cookbooks/package/libraries/helpers/settings_helper.rb:172:in `generate_config'
  /opt/gitlab/embedded/cookbooks/cache/cookbooks/gitlab/recipes/config.rb:26:in `from_file'
  /opt/gitlab/embedded/cookbooks/cache/cookbooks/gitlab/recipes/default.rb:26:in `from_file'


"cannot modify limit: Operation not permitted" while using the Docker image
```

**Comment by Xide** [comment]
Hi @davStar,

There are two different issues there, the first one being the `ulimit` permission denied, which does not affect normal operations according to [this Gitlab thread](https://gitlab.com/gitlab-org/omnibus-gitlab/issues/1350).

The other one is the `undefined method '+' for nil:NilClass`, which if i remember correctly, we encountered a variant some months ago. At the time, it was caused because we didn't ran the database migrations after an update, and the application expected a table to exists, it failed when the undelying DAO returned a nil object. You can find a similar issue [on the Gitlab tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues/21841).

I see that your [gitlab role](https://github.com/lightpharosio/allspark/blob/master/onebox/roles/gitlab/tasks/main.yml) does not include the [patch for this issue](https://github.com/actiniumio/allspark/blob/master/roles/gitlab/handlers/main.yml). 
Is it possible that the image was updated moments before you ran into this issue ? 

If so, you can manually run a `docker exec gitlab bash -c 'set -xe; gitlab-rake db:migrate;'` to run the migrations, restart your container and it should restart correctly (Make sure to backup the docker volume before the operation).

Otherwise, i'll need a bit more context to to help you there, could you post a more defailed log 
with the object that was expected and returned `nil` ?

Regards,
